### ISSUE TITLE
Error on updating app

### ISSUE THREAD

**Issue by uniconstructor** [YunoHost-Apps/cac-proxy_ynh#12]
Steps to reproduce:
1) go to yunohost admin panel
2) click "update app" on cac-proxy

Actual result: error message, failed update.

![2023-16-28_05-16](https://github.com/YunoHost-Apps/cac-proxy_ynh/assets/1384545/dba53b54-538f-4447-95b4-ed97613d299e)

Logs: https://paste.yunohost.org/raw/nafisuqivu
[nafisuqivu.log](https://github.com/YunoHost-Apps/cac-proxy_ynh/files/12744866/nafisuqivu.log)

**Comment by gcollin** [comment]
Hi, I've just tested again upgrading from 1.1 to 1.2 in my test system and it just worked fine.
Give me a bit of time to check in the upgrade script.

**Comment by gcollin** [comment]
Thanks for creating the issue, there were indeed a bug in the backup script, in case you didn't enable dev access.
The fix will be in the next release, available in a few days.
If you don't want to wait, you can just run
` touch /etc/sudoers.d/cac-proxy-sudoers `
in your server before running the update. It should work.

**Comment by gcollin** [comment]
Fixed in release 1.2.0~ynh2

**Comment by uniconstructor** [comment]
Awesome! Thanks!
