### ISSUE TITLE
Upon removing chromium is not uninstalled

### ISSUE THREAD

**Issue by orhtej2** [YunoHost-Apps/cac-proxy_ynh#19]
Perhaps it would be beneficial to install chromium via dedicated helper, otherwise it's left dangling after app removal.

**Comment by gcollin** [comment]
Ah you're right. I'm using the puppeteer script to install chromium but do nothing for uninstalling it.
I'll fix that

**Comment by gcollin** [comment]
In fact I checked and a special version of chromium is being installed on cac-proxy/.cache directory and it gets removed on uninstall.
So I don't know what part of Chromium is left after desinstallation ?

**Comment by orhtej2** [comment]
🤔 I got `chromium` installed on my server and I remember testing `cac-proxy`, given it's the only app that mentions it I assumed it came from here.

🤷 sorry for red herring.

**Comment by gcollin** [comment]
No problem. it didn't fit to your needs ?

**Comment by orhtej2** [comment]
Haha no, I'm not the target audience, I was just testing some (CI?) issue reported somewhere IIRC.
